In [1]:
import math
import datetime
import os
os.getcwd()

'C:\\Users\\Nilotpal.Choudhury\\OneDrive - Shell\\Documents\\Trading & Supply\\2020\\G2G Report Analysis\\Data Model'

In [2]:
os.chdir('C:\\Users\\Nilotpal.Choudhury\\OneDrive - Shell\\Documents\\Trading & Supply\\2020\\G2G Report Analysis\\TT reporting Trend\\2020_G2G Analysis')

In [3]:
os.getcwd()

'C:\\Users\\Nilotpal.Choudhury\\OneDrive - Shell\\Documents\\Trading & Supply\\2020\\G2G Report Analysis\\TT reporting Trend\\2020_G2G Analysis'

In [4]:
import pandas as pd
import numpy as np

In [5]:
dataset = pd.read_excel("G2G Sep'20.xlsx",sheet_name="Sep'20",usecols = "E:N,AB:AC",header=1)

In [6]:
dataset.replace(r'^\s*$',np.nan, regex=True,inplace=True)
dataset.fillna(0,axis=1,inplace=True)

In [7]:
dataset

,Month,Plant,Date of loading,Truck No,Haulier,Product,ULP,SVPM,HSD,SVPD,Depot In,Depot Out
0,2020-09-30,I314,2020-09-01,GJ12BW1330,ARPL,HSD,0.0,0.0,11.0,0.0,10:38:00,17:23:00
1,2020-09-30,I314,2020-09-01,GJ12BW1330,ARPL,HSD,12.0,0.0,6.0,0.0,10:38:00,17:23:00
2,2020-09-30,I315,2020-09-01,GJ12BX1010,ARPL,MS,11.0,0.0,0.0,0.0,13:27:00,17:00:00
3,2020-09-30,I315,2020-09-01,GJ12BX1010,ARPL,MS,12.0,6.0,0.0,0.0,13:27:00,17:00:00
4,2020-09-30,I315,2020-09-01,GJ12AZ9738,ARPL,MS/HSD,10.0,0.0,14.0,0.0,13:56:00,16:30:00
...,...,...,...,...,...,...,...,...,...,...,...,...
2056,2020-09-30,I304,2020-09-30,TN86D4888,VELAN,ML,19.0,10.0,0.0,0.0,08:29:21,12:19:51
2057,2020-09-30,I437,2020-09-01,TN56P0021,VELAN,ML,12.0,6.0,10.0,0.0,08:03:03,11:37:00
2058,2020-09-30,I437,2020-09-12,TN56P0021,VELAN,ML,10.0,0.0,19.0,0.0,11:40:34,14:55:11
2059,2020-09-30,I437,2020-09-22,TN56M9219,VELAN,ML,12.0,6.0,10.0,0.0,08:58:15,12:51:29
2060,2020-09-30,I437,2020-09-30,TN52Q5522,VELAN,ML,12.0,6.0,10.0,0.0,12:57:12,18:13:03

In [8]:
dataset.set_axis(['Month','Plant','Date of Loading','Truck No','Hauler','Product','ULP','SVPM','HSD','SVPD','Depot In','Depot Out'],
                axis='columns',inplace=True)

In [9]:
dataset

,Month,Plant,Date of Loading,Truck No,Hauler,Product,ULP,SVPM,HSD,SVPD,Depot In,Depot Out
0,2020-09-30,I314,2020-09-01,GJ12BW1330,ARPL,HSD,0.0,0.0,11.0,0.0,10:38:00,17:23:00
1,2020-09-30,I314,2020-09-01,GJ12BW1330,ARPL,HSD,12.0,0.0,6.0,0.0,10:38:00,17:23:00
2,2020-09-30,I315,2020-09-01,GJ12BX1010,ARPL,MS,11.0,0.0,0.0,0.0,13:27:00,17:00:00
3,2020-09-30,I315,2020-09-01,GJ12BX1010,ARPL,MS,12.0,6.0,0.0,0.0,13:27:00,17:00:00
4,2020-09-30,I315,2020-09-01,GJ12AZ9738,ARPL,MS/HSD,10.0,0.0,14.0,0.0,13:56:00,16:30:00
...,...,...,...,...,...,...,...,...,...,...,...,...
2056,2020-09-30,I304,2020-09-30,TN86D4888,VELAN,ML,19.0,10.0,0.0,0.0,08:29:21,12:19:51
2057,2020-09-30,I437,2020-09-01,TN56P0021,VELAN,ML,12.0,6.0,10.0,0.0,08:03:03,11:37:00
2058,2020-09-30,I437,2020-09-12,TN56P0021,VELAN,ML,10.0,0.0,19.0,0.0,11:40:34,14:55:11
2059,2020-09-30,I437,2020-09-22,TN56M9219,VELAN,ML,12.0,6.0,10.0,0.0,08:58:15,12:51:29
2060,2020-09-30,I437,2020-09-30,TN52Q5522,VELAN,ML,12.0,6.0,10.0,0.0,12:57:12,18:13:03

In [10]:
dataset['MS'] = dataset['ULP'] + dataset['SVPM']
dataset['AGO'] = dataset['HSD'] + dataset['SVPD']

In [11]:
dataset.drop(['Hauler','Product','ULP','SVPM','HSD','SVPD'],axis=1,inplace=True)

In [12]:
for i in range(len(dataset)):
    if isinstance(dataset.loc[i,'Month'],datetime.date) == False:
        dataset.loc[i,'Month'] = math.nan
        
    if isinstance(dataset.loc[i,'Date of Loading'],datetime.date) == False:
        dataset.loc[i,'Month'] = math.nan
        
    if isinstance(dataset.loc[i,'Depot In'],datetime.time) == False:
        dataset.loc[i,'Month'] = math.nan
        
    if isinstance(dataset.loc[i,'Depot Out'],datetime.time) == False:
        dataset.loc[i,'Month'] = math.nan

In [13]:
dataset.dropna(axis=0,inplace=True)

In [14]:
dataset.columns

Index(['Month', 'Plant', 'Date of Loading', 'Truck No', 'Depot In',
       'Depot Out', 'MS', 'AGO'],
      dtype='object')

In [15]:
zz = dataset.groupby(['Month', 'Plant', 'Date of Loading', 'Truck No', 'Depot In',
       'Depot Out']).agg({'MS':sum,'AGO':sum}).reset_index()

In [16]:
zz['Prod Type'] = np.where((zz['MS']>0) & (zz['AGO']>0),"MPL","Single")

In [17]:
zz

,Month,Plant,Date of Loading,Truck No,Depot In,Depot Out,MS,AGO,Prod Type
0,2020-09-30,I302,2020-09-01,KA01AE3464,13:00:00,15:00:00,10.0,14.0,MPL
1,2020-09-30,I302,2020-09-01,KA01AE3613,13:00:00,17:26:00,10.0,14.0,MPL
2,2020-09-30,I302,2020-09-01,KA01AE3882,14:00:00,16:58:00,10.0,14.0,MPL
3,2020-09-30,I302,2020-09-01,KA01AE5301,10:22:00,12:42:00,24.0,0.0,Single
4,2020-09-30,I302,2020-09-01,KA01AF2101,08:54:00,11:30:00,24.0,0.0,Single
...,...,...,...,...,...,...,...,...,...
1668,2020-09-30,I493,2020-09-24,GJ12AZ8551,08:13:00,13:17:00,24.0,0.0,Single
1669,2020-09-30,i315,2020-09-03,GJ01DV8221,07:24:00,11:01:00,24.0,0.0,Single
1670,2020-09-30,i315,2020-09-04,GJ01DY4988,07:23:00,10:15:00,14.0,10.0,MPL
1671,2020-09-30,i315,2020-09-08,GJ01DV6518,20:39:00,23:59:00,14.0,10.0,MPL
1672,2020-09-30,i315,2020-09-08,GJ01DX7329,20:38:00,23:44:00,14.0,10.0,MPL

In [18]:
path = 'C:\\Users\\Nilotpal.Choudhury\\OneDrive - Shell\\Documents\\Trading & Supply\\2020\G2G Report Analysis\\Data Model\\Monthly Data Files\\Single-MPL_Keys\\'
zz.to_csv(path+'Sep-20.csv',index=False)